import {
  Users,
  CreditCard,
  Cog,
  Shield,
  Plug,
  FileCode,
  Globe,
  Smile,
  Ticket,
  HardDrive,
  Warehouse,
  Building,
  LayoutGrid,
  History,
  KanbanSquare,
  Hash,
  User,
} from 'lucide-react';

export const personalSettingsItems = [
  {
    icon: User,
    title: 'Profile & Account',
    description: 'Manage your personal profile, password, and account settings.',
    href: '/user-profile',
    target: '_self',
  },
];

export const settingsItems = [
  {
    icon: Building,
    title: 'Company Settings',
    description: 'Manage your company info and subdomain.',
    href: '/settings/company',
    target: '_self',
  },
  {
    icon: Users,
    title: 'Users & Permissions',
    description: 'Manage users, roles, permissions, and enterprise identity through WorkOS.',
    href: '/settings/users',
    target: '_self',
  },
  {
    icon: LayoutGrid,
    title: 'Modules',
    description: 'Enable or disable application modules.',
    href: '/settings/modules',
    target: '_self',
  },
    {
    icon: Hash,
    title: 'Numbering Schemes',
    description: 'Customize ID prefixes and suffixes.',
    href: '/settings/numbering',
    target: '_self',
  },
  {
    icon: CreditCard,
    title: 'Billing & Subscriptions',
    description: 'Manage your payment methods and plan.',
    href: '/settings/billing',
    target: '_self',
  },
  {
    icon: Cog,
    title: 'Custom Fields',
    description: 'Create and manage custom fields for modules.',
    href: '/settings/fields',
    target: '_self',
  },
  {
    icon: KanbanSquare,
    title: 'Project Management',
    description: 'Configure project statuses and templates.',
    href: '/settings/projects',
    target: '_self',
  },
  {
    icon: Ticket,
    title: 'Ticket Management',
    description: 'Manage queues, statuses, and priorities.',
    href: '/settings/tickets',
    target: '_self',
  },
  {
    icon: HardDrive,
    title: 'Asset Management',
    description: 'Manage asset statuses, categories, and locations.',
    href: '/settings/assets',
    target: '_self',
  },
  {
    icon: Warehouse,
    title: 'Inventory Management',
    description: 'Manage inventory categories, locations, and suppliers.',
    href: '/settings/inventory',
    target: '_self',
  },
  {
    icon: History,
    title: 'Change Management',
    description: 'Manage statuses, risk, and impact levels for changes.',
    href: '/settings/change-management',
    target: '_self',
  },
  {
    icon: Shield,
    title: 'SLA Management',
    description: 'Define and manage Service Level Agreements.',
    href: '/settings/sla',
    target: '_self',
  },
  {
    icon: Smile,
    title: 'CSAT Management',
    description: 'Configure and monitor customer satisfaction surveys.',
    href: '/settings/csat',
    target: '_self',
  },
  {
    icon: FileCode,
    title: 'Script Repository',
    description: 'Manage and generate scripts for automation.',
    href: '/settings/script-repository',
    target: '_self',
  },
  {
    icon: Plug,
    title: 'Integrations',
    description: 'Connect with RMM and other third-party apps.',
    href: '/settings/integrations',
    target: '_self',
  },
  {
    icon: Globe,
    title: 'Client Portal',
    description: 'Preview the client-facing portal.',
    href: '/portal/login',
    target: '_blank',
  },
];
